version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: rag_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    environment:
      QDRANT__SERVICE__ENABLE_CORS: "true"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/readyz"]
      interval: 5s
      timeout: 3s
      retries: 20
